# Changes here will be overwritten by Copier
_commit: 2901eb6
_src_path: https://github.com/zsxoff/python-template
module_name: pyinfra-webserver
project_description: Web server with pyinfra
project_name: pyinfra-webserver
